version: "3.9"

services:
  backend:
    container_name: backend
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - notes
    environment:
      - POSTGRES_URL=${POSTGRES_URL}
      - PORT=${PORT}

  postgres:
    image: postgres:16.2-alpine3.19
    container_name: postgres
    restart: always
    volumes:
      - postgres:/var/lib/postgresql/data
    healthcheck:
      test:
        [
          "CMD",
          "pg_isready",
          "-q",
          "-h",
          "localhost",
          "-U",
          "${POSTGRES_USER}",
          "-d",
          "${POSTGRES_DB}",
        ]
      interval: 5s
      timeout: 3s
      retries: 10
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - notes

volumes:
  postgres:
  caddy_data:
  caddy_config:

networks:
  notes:
