services:
  backend:
    build:
      context: ../backend
      dockerfile: docker/Dockerfile.pre

  caddy:
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
