version: "3.9"

services:
  backend:
    container_name: backend
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      BASE_URL_V1: ${BASE_URL_V1}
      BACKEND_PORT: ${BACKEND_PORT}
      POSTGRES_URL: ${POSTGRES_URL}
      ALLOW_ORIGINS: ${ALLOW_ORIGINS}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
    networks:
      - notes

  postgres:
    image: postgres:16.2-alpine3.19
    container_name: postgres
    restart: always
    volumes:
      - postgres:/var/lib/postgresql/data
    healthcheck:
      test:
        [
          "CMD",
          "pg_isready",
          "-q",
          "-h",
          "localhost",
          "-U",
          "${POSTGRES_USER}",
          "-d",
          "${POSTGRES_DB}",
        ]
      interval: 5s
      timeout: 3s
      retries: 10
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - notes

  caddy:
    image: caddy:2.7.6-alpine
    container_name: caddy
    depends_on:
      - backend
    ports:
      - 80:80
      - 443:443
    environment:
      BACKEND_PORT: ${BACKEND_PORT}
    networks:
      - notes

volumes:
  postgres:
  caddy_data:
  caddy_config:

networks:
  notes:
