services:
  backend:
    build:
      context: ../backend
      dockerfile: docker/Dockerfile.dev
    volumes:
      - ../backend:/app

  adminer:
    image: adminer:latest
    container_name: adminer
    restart: unless-stopped
    environment:
      ADMINER_DESIGN: "nette" # themes: https://github.com/vrana/adminer/tree/master/plugins
    networks:
      - notes

  caddy:
    image: caddy:2.7.6-alpine
    container_name: caddy
    depends_on:
      - backend
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./caddy/Caddyfile.dev:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - notes
