FROM golang:1.22.1-alpine

RUN go install github.com/githubnemo/CompileDaemon@v1.4.0

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download && go mod verify

COPY . .

EXPOSE 8000

CMD CompileDaemon -log-prefix=false -build="go build -o bin/quintos cmd/quintos/main.go" -command="bin/quintos"
