FROM golang:1.22.1-alpine

RUN go install github.com/githubnemo/CompileDaemon@latest

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download && go mod verify

COPY . .

CMD CompileDaemon -log-prefix=false -build="go build -o build/main ." -command="./build/main"
